version: 3

tasks:
  smoke_test:
    cmds:
      - ./bin/smoke-test {{.CLI_ARGS}}
    deps: 
      - build_smoke_test
    method: none
    silent: true

  build_smoke_test:
    cmds:
      - odin build smoke_test -o:none -debug -out:./bin/smoke-test
    sources:
      - ./smoke_test/**/*.odin
    generates:
      - ./bin/smoke-test
    silent: true

  prime_time:
    cmds:
      - ./bin/prime-time {{.CLI_ARGS}}
    deps: 
      - build_prime_time
    method: none
    silent: true

  build_prime_time:
    cmds:
      - odin build prime_time -o:none -debug -out:./bin/prime-time
    sources:
      - ./prime_time/**/*.odin
    generates:
      - ./bin/prime-time
    silent: true

  test_prime_time:
    cmds:
      - odin test prime_time -o:none -debug -out:./bin/test-prime-test
    sources:
      - ./prime_time/**/*.odin
    generates:
      - ./bin/test-prime-test
    silent: true

  clean:
    cmds:
      - rm -rf ./bin/*
    silent: true
    method: none

interval: 100ms
